//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class KOPStoreEntities : DbContext
    {
        public KOPStoreEntities()
            : base("name=KOPStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblProductGroup> tblProductGroups { get; set; }
        public DbSet<tblProduct> tblProducts { get; set; }
        public DbSet<vProduct> vProducts { get; set; }
        public DbSet<tblUserLevel> tblUserLevels { get; set; }
        public DbSet<tblUsers> tblUsers { get; set; }
        public DbSet<vUsers> vUsers1 { get; set; }
        public DbSet<tblLoginLog> tblLoginLogs { get; set; }
        public DbSet<tblBrand> tblBrands { get; set; }
        public DbSet<tblColor> tblColors { get; set; }
        public DbSet<tblCountry> tblCountries { get; set; }
        public DbSet<tblMaterial> tblMaterials { get; set; }
        public DbSet<tblSize> tblSizes { get; set; }
        public DbSet<tblGender> tblGenders { get; set; }
        public DbSet<tblProductsDetail> tblProductsDetails { get; set; }
        public DbSet<tblCustomer> tblCustomers { get; set; }
        public DbSet<tblInputFactorMain> tblInputFactorMains { get; set; }
        public DbSet<tblInputFactorDetail> tblInputFactorDetails { get; set; }
        public DbSet<tblInpPayment> tblInpPayments { get; set; }
        public DbSet<tbloutPayment> tbloutPayments { get; set; }
        public DbSet<tblOutputFactorDetail> tblOutputFactorDetails { get; set; }
        public DbSet<tblOutputFactorMain> tblOutputFactorMains { get; set; }
        public DbSet<tblMojoodi> tblMojoodis { get; set; }
        public DbSet<tblTakhsisAmval> tblTakhsisAmvals { get; set; }
        public DbSet<tblVendor> tblVendors { get; set; }
        public DbSet<tblServiceDetail> tblServiceDetails { get; set; }
        public DbSet<vAmvalCustomer> vAmvalCustomers { get; set; }
        public DbSet<tblEsghatAmval> tblEsghatAmvals { get; set; }
        public DbSet<vEshghatAmval> vEshghatAmvals { get; set; }
        public DbSet<tblServiceMain> tblServiceMains { get; set; }
        public DbSet<vProductDetailFilter> vProductDetailFilters { get; set; }
        public DbSet<vProductDetail> vProductDetails { get; set; }
        public DbSet<vInputFactorFull> vInputFactorFulls { get; set; }
        public DbSet<vOutputFactorFull> vOutputFactorFulls { get; set; }
        public DbSet<vAmval> vAmvals { get; set; }
        public DbSet<tblAction> tblActions { get; set; }
        public DbSet<tblAmvalAction> tblAmvalActions { get; set; }
        public DbSet<tblAmval> tblAmvals { get; set; }
        public DbSet<vServiceFull> vServiceFulls { get; set; }
        public DbSet<vGardeshAmval> vGardeshAmvals { get; set; }
        public DbSet<vActionAmval> vActionAmvals { get; set; }
    
        public virtual int sp_UpdateMojoodi(Nullable<int> pdid, Nullable<int> num)
        {
            var pdidParameter = pdid.HasValue ?
                new ObjectParameter("pdid", pdid) :
                new ObjectParameter("pdid", typeof(int));
    
            var numParameter = num.HasValue ?
                new ObjectParameter("num", num) :
                new ObjectParameter("num", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateMojoodi", pdidParameter, numParameter);
        }
    
        public virtual ObjectResult<sp_FilterCustomer_Result> sp_FilterCustomer(string searchValue)
        {
            var searchValueParameter = searchValue != null ?
                new ObjectParameter("searchValue", searchValue) :
                new ObjectParameter("searchValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FilterCustomer_Result>("sp_FilterCustomer", searchValueParameter);
        }
    
        public virtual ObjectResult<sp_Tajmi_Result> sp_Tajmi(Nullable<short> p, string d1, string d2)
        {
            var pParameter = p.HasValue ?
                new ObjectParameter("p", p) :
                new ObjectParameter("p", typeof(short));
    
            var d1Parameter = d1 != null ?
                new ObjectParameter("d1", d1) :
                new ObjectParameter("d1", typeof(string));
    
            var d2Parameter = d2 != null ?
                new ObjectParameter("d2", d2) :
                new ObjectParameter("d2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Tajmi_Result>("sp_Tajmi", pParameter, d1Parameter, d2Parameter);
        }
    
        public virtual ObjectResult<sp_TajmiMasrafiProduct_Result> sp_TajmiMasrafiProduct(string d1, string d2)
        {
            var d1Parameter = d1 != null ?
                new ObjectParameter("d1", d1) :
                new ObjectParameter("d1", typeof(string));
    
            var d2Parameter = d2 != null ?
                new ObjectParameter("d2", d2) :
                new ObjectParameter("d2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TajmiMasrafiProduct_Result>("sp_TajmiMasrafiProduct", d1Parameter, d2Parameter);
        }
    
        public virtual ObjectResult<sp_TafsilUsersDate_Result> sp_TafsilUsersDate(string d1, string d2)
        {
            var d1Parameter = d1 != null ?
                new ObjectParameter("d1", d1) :
                new ObjectParameter("d1", typeof(string));
    
            var d2Parameter = d2 != null ?
                new ObjectParameter("d2", d2) :
                new ObjectParameter("d2", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TafsilUsersDate_Result>("sp_TafsilUsersDate", d1Parameter, d2Parameter);
        }
    
        public virtual ObjectResult<sp_MojoodiLessThan5_Result> sp_MojoodiLessThan5(Nullable<int> n1, Nullable<int> n2)
        {
            var n1Parameter = n1.HasValue ?
                new ObjectParameter("n1", n1) :
                new ObjectParameter("n1", typeof(int));
    
            var n2Parameter = n2.HasValue ?
                new ObjectParameter("n2", n2) :
                new ObjectParameter("n2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MojoodiLessThan5_Result>("sp_MojoodiLessThan5", n1Parameter, n2Parameter);
        }
    
        public virtual ObjectResult<sp_TheLastFivePersonWhoTake_Result> sp_TheLastFivePersonWhoTake()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TheLastFivePersonWhoTake_Result>("sp_TheLastFivePersonWhoTake");
        }
    
        public virtual ObjectResult<sp_FiveMostCustomerOut_Result> sp_FiveMostCustomerOut(Nullable<System.DateTime> d1, Nullable<System.DateTime> d2)
        {
            var d1Parameter = d1.HasValue ?
                new ObjectParameter("d1", d1) :
                new ObjectParameter("d1", typeof(System.DateTime));
    
            var d2Parameter = d2.HasValue ?
                new ObjectParameter("d2", d2) :
                new ObjectParameter("d2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FiveMostCustomerOut_Result>("sp_FiveMostCustomerOut", d1Parameter, d2Parameter);
        }
    
        public virtual ObjectResult<sp_FiveMostProductOut_Result> sp_FiveMostProductOut(Nullable<System.DateTime> d1, Nullable<System.DateTime> d2)
        {
            var d1Parameter = d1.HasValue ?
                new ObjectParameter("d1", d1) :
                new ObjectParameter("d1", typeof(System.DateTime));
    
            var d2Parameter = d2.HasValue ?
                new ObjectParameter("d2", d2) :
                new ObjectParameter("d2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_FiveMostProductOut_Result>("sp_FiveMostProductOut", d1Parameter, d2Parameter);
        }
    
        public virtual ObjectResult<sp_RepAmvalAssignToCustomer_Result> sp_RepAmvalAssignToCustomer(Nullable<int> cid, Nullable<int> op)
        {
            var cidParameter = cid.HasValue ?
                new ObjectParameter("cid", cid) :
                new ObjectParameter("cid", typeof(int));
    
            var opParameter = op.HasValue ?
                new ObjectParameter("op", op) :
                new ObjectParameter("op", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RepAmvalAssignToCustomer_Result>("sp_RepAmvalAssignToCustomer", cidParameter, opParameter);
        }
    }
}
