//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAction
    {
        public tblAction()
        {
            this.tblAmvalActions = new HashSet<tblAmvalAction>();
        }
    
        public short actionId { get; set; }
        public string actionName { get; set; }
        public string actionFarsiName { get; set; }
    
        public virtual ICollection<tblAmvalAction> tblAmvalActions { get; set; }
    }
}
