//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAmvalAction
    {
        public int radifId { get; set; }
        public string amval { get; set; }
        public Nullable<short> actionId { get; set; }
        public Nullable<System.DateTime> actionDate { get; set; }
    
        public virtual tblAction tblAction { get; set; }
        public virtual tblAmval tblAmval { get; set; }
    }
}
