//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public tblCustomer()
        {
            this.tblInputFactorMains = new HashSet<tblInputFactorMain>();
            this.tblOutputFactorMains = new HashSet<tblOutputFactorMain>();
            this.tblTakhsisAmvals = new HashSet<tblTakhsisAmval>();
            this.tblServiceDetails = new HashSet<tblServiceDetail>();
            this.tblEsghatAmvals = new HashSet<tblEsghatAmval>();
        }
    
        public short customerId { get; set; }
        public string customerFName { get; set; }
        public string customerLName { get; set; }
        public string customerMobile { get; set; }
        public string customerPhone { get; set; }
        public string customerAddress { get; set; }
        public string customerCompany { get; set; }
    
        public virtual ICollection<tblInputFactorMain> tblInputFactorMains { get; set; }
        public virtual ICollection<tblOutputFactorMain> tblOutputFactorMains { get; set; }
        public virtual ICollection<tblTakhsisAmval> tblTakhsisAmvals { get; set; }
        public virtual ICollection<tblServiceDetail> tblServiceDetails { get; set; }
        public virtual ICollection<tblEsghatAmval> tblEsghatAmvals { get; set; }
    }
}
