//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInputFactorDetail
    {
        public int inpFactorId { get; set; }
        public int inpFactorDetailId { get; set; }
        public int pdId { get; set; }
        public short quantity { get; set; }
        public Nullable<decimal> unitPrice { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public string inpDetailDesc { get; set; }
    
        public virtual tblInputFactorMain tblInputFactorMain { get; set; }
        public virtual tblProductsDetail tblProductsDetail { get; set; }
    }
}
