//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoginLog
    {
        public int radif { get; set; }
        public string username { get; set; }
        public string xTime { get; set; }
        public string xDate { get; set; }
        public string ipAddress { get; set; }
    }
}
