//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbloutPayment
    {
        public int outFactorId { get; set; }
        public short radif { get; set; }
        public Nullable<System.DateTime> checkDate { get; set; }
        public Nullable<decimal> giveMoney { get; set; }
        public Nullable<short> paid { get; set; }
        public Nullable<System.DateTime> paidDate { get; set; }
    
        public virtual tblOutputFactorMain tblOutputFactorMain { get; set; }
    }
}
