//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductGroup
    {
        public tblProductGroup()
        {
            this.tblProducts = new HashSet<tblProduct>();
        }
    
        public int productGroupId { get; set; }
        public string productGroupName { get; set; }
    
        public virtual ICollection<tblProduct> tblProducts { get; set; }
    }
}
