//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductsDetail
    {
        public tblProductsDetail()
        {
            this.tblInputFactorDetails = new HashSet<tblInputFactorDetail>();
            this.tblOutputFactorDetails = new HashSet<tblOutputFactorDetail>();
            this.tblTakhsisAmvals = new HashSet<tblTakhsisAmval>();
            this.tblServiceDetails = new HashSet<tblServiceDetail>();
            this.tblEsghatAmvals = new HashSet<tblEsghatAmval>();
        }
    
        public int pdId { get; set; }
        public int productId { get; set; }
        public Nullable<short> pBrand { get; set; }
        public Nullable<short> pMaterial { get; set; }
        public Nullable<short> pColor { get; set; }
        public Nullable<short> pSize { get; set; }
        public Nullable<short> pGender { get; set; }
        public Nullable<short> pCountry { get; set; }
        public string pDescription { get; set; }
        public string pImage { get; set; }
    
        public virtual tblBrand tblBrand { get; set; }
        public virtual tblColor tblColor { get; set; }
        public virtual tblCountry tblCountry { get; set; }
        public virtual tblGender tblGender { get; set; }
        public virtual tblMaterial tblMaterial { get; set; }
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblSize tblSize { get; set; }
        public virtual ICollection<tblInputFactorDetail> tblInputFactorDetails { get; set; }
        public virtual ICollection<tblOutputFactorDetail> tblOutputFactorDetails { get; set; }
        public virtual tblMojoodi tblMojoodi { get; set; }
        public virtual ICollection<tblTakhsisAmval> tblTakhsisAmvals { get; set; }
        public virtual ICollection<tblServiceDetail> tblServiceDetails { get; set; }
        public virtual ICollection<tblEsghatAmval> tblEsghatAmvals { get; set; }
    }
}
