//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceDetail
    {
        public int serviceId { get; set; }
        public int serviceDetailId { get; set; }
        public Nullable<int> pdid { get; set; }
        public string amval { get; set; }
        public Nullable<short> customerId { get; set; }
        public Nullable<decimal> servicePrice { get; set; }
        public string serviceDetailDesc { get; set; }
    
        public virtual tblCustomer tblCustomer { get; set; }
        public virtual tblProductsDetail tblProductsDetail { get; set; }
        public virtual tblServiceMain tblServiceMain { get; set; }
        public virtual tblAmval tblAmval { get; set; }
    }
}
