//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblServiceMain
    {
        public tblServiceMain()
        {
            this.tblServiceDetails = new HashSet<tblServiceDetail>();
        }
    
        public int serviceId { get; set; }
        public Nullable<System.DateTime> serviceDate { get; set; }
        public Nullable<short> vendorId { get; set; }
        public string serviceDescription { get; set; }
        public Nullable<decimal> serviceTotalPrice { get; set; }
        public Nullable<int> userid { get; set; }
    
        public virtual ICollection<tblServiceDetail> tblServiceDetails { get; set; }
        public virtual tblVendor tblVendor { get; set; }
    }
}
