//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsers
    {
        public tblUsers()
        {
            this.tblInputFactorMains = new HashSet<tblInputFactorMain>();
            this.tblOutputFactorMains = new HashSet<tblOutputFactorMain>();
            this.tblTakhsisAmvals = new HashSet<tblTakhsisAmval>();
        }
    
        public int Id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<short> levelCode { get; set; }
        public bool active { get; set; }
    
        public virtual tblUserLevel tblUserLevel { get; set; }
        public virtual ICollection<tblInputFactorMain> tblInputFactorMains { get; set; }
        public virtual ICollection<tblOutputFactorMain> tblOutputFactorMains { get; set; }
        public virtual ICollection<tblTakhsisAmval> tblTakhsisAmvals { get; set; }
    }
}
