//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class vActionAmval
    {
        public string amval { get; set; }
        public Nullable<short> actionId { get; set; }
        public string actionFarsiName { get; set; }
        public Nullable<System.DateTime> actionDate { get; set; }
        public string actionName { get; set; }
        public string productNameX { get; set; }
        public short customerId { get; set; }
        public string customerFName { get; set; }
        public string customerLName { get; set; }
        public string myDate { get; set; }
    }
}
