//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAmvalCustomer
    {
        public string amval { get; set; }
        public string customerFName { get; set; }
        public string customerLName { get; set; }
        public Nullable<bool> active { get; set; }
        public Nullable<bool> esghat { get; set; }
        public string productName { get; set; }
        public short customerId { get; set; }
        public int radif { get; set; }
        public int pdId { get; set; }
    }
}
