//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAmval
    {
        public string amval { get; set; }
        public int pdId { get; set; }
        public string productNameX { get; set; }
        public string myDate { get; set; }
        public Nullable<decimal> buyPrice { get; set; }
        public string sapPR { get; set; }
        public string serialNumber { get; set; }
        public string barcodeNumber { get; set; }
        public string description { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> buyDate { get; set; }
    }
}
