//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class vEshghatAmval
    {
        public string amval { get; set; }
        public string ProductName { get; set; }
        public string CustomerName { get; set; }
        public string myDate { get; set; }
        public string esghatDescription { get; set; }
        public Nullable<System.DateTime> esghatDate { get; set; }
    }
}
