//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOutputFactorFull
    {
        public Nullable<int> outFactorId { get; set; }
        public Nullable<short> CustomerId { get; set; }
        public string CustomerName { get; set; }
        public Nullable<System.DateTime> outFactorDate { get; set; }
        public string myDate { get; set; }
        public string outFactorTime { get; set; }
        public string username { get; set; }
        public string outFactorDesc { get; set; }
        public int outFactorDetailId { get; set; }
        public int pdId { get; set; }
        public string productName { get; set; }
        public string productGroupName { get; set; }
        public Nullable<short> pBrand { get; set; }
        public string brandName { get; set; }
        public Nullable<short> pColor { get; set; }
        public string colorName { get; set; }
        public Nullable<short> pMaterial { get; set; }
        public string materialName { get; set; }
        public Nullable<short> pSize { get; set; }
        public string sizeName { get; set; }
        public Nullable<short> pGender { get; set; }
        public string genderName { get; set; }
        public Nullable<short> pCountry { get; set; }
        public string countryName { get; set; }
        public string pDescription { get; set; }
        public string pImage { get; set; }
        public short quantity { get; set; }
        public Nullable<decimal> unitPrice { get; set; }
        public Nullable<double> discount { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public string outDetailDesc { get; set; }
    }
}
