//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOP_Store.Models.DataBaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class vServiceFull
    {
        public int serviceId { get; set; }
        public Nullable<System.DateTime> serviceDate { get; set; }
        public string myDate { get; set; }
        public Nullable<short> vendorId { get; set; }
        public string companyName { get; set; }
        public string vendorName { get; set; }
        public string serviceDescription { get; set; }
        public Nullable<decimal> serviceTotalPrice { get; set; }
        public string productNameX { get; set; }
        public string customerLName { get; set; }
        public string customerFName { get; set; }
        public Nullable<decimal> servicePrice { get; set; }
        public string serviceDetailDesc { get; set; }
        public Nullable<int> pdid { get; set; }
        public Nullable<short> customerId { get; set; }
        public string amval { get; set; }
    }
}
